FROM reach.base

WORKDIR /opt/reach

COPY ./requirements.tests.txt /opt/reach/requirements.tests.txt


RUN pip install -U pip && \
        python3 -m pip install -r /opt/reach/requirements.tests.txt


COPY ./scraper /opt/reach/scraper
COPY ./parser /opt/reach/parser
COPY ./extracter /opt/reach/extracter

ENTRYPOINT ["pytest", "/opt/reach"]
