apiVersion: v1
kind: PersistentVolume
metadata:
  name: argo-elasticsearch-volume
  namespace: argo
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argo-elasticsearch-claim
  namespace: argo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: argo
  annotations:
    kubernetes.io/change-cause: N/A
spec:
  selector:
    matchLabels:
      app: elasticsearch
  serviceName: "elasticsearch"
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      initContainers:
      # NOTE:
      # This is to fix the permission on the volume
      # By default elasticsearch container is not run as
      # non root user.
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_notes_for_production_use_and_defaults
      - name: fix-volume-permission
        image: busybox
        command:
        - sh
        - -c
        - chown -R 1000:1000 /usr/share/elasticsearch/data
        securityContext:
          privileged: true
        volumeMounts:
        - name: argo-elasticsearch-claim
          mountPath: /usr/share/elasticsearch/data
      # To increase the ulimit
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_notes_for_production_use_and_defaults
      - name: increase-ulimit
        image: busybox
        command:
        - sh
        - -c
        - ulimit -n 65536
        securityContext:
          privileged: true
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
        ports:
        - containerPort: 9200
        env:
          - name: discovery.type
            value: "single-node"
          - name: bootstrap.memory_lock
            value: "true"
          - name: ES_JAVA_OPTS
            value: "-Xms2G -Xmx2G"
        resources:
          requests:
            cpu: "250m"
            memory: "3Gi"
          limits:
            cpu: "2000m"
            memory: "3Gi"
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: argo-elasticsearch-claim
      volumes:
        - name: argo-elasticsearch-claim
          persistentVolumeClaim:
            claimName: argo-elasticsearch-claim
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: argo
  labels:
    app: elasticsearch
spec:
  ports:
  - port: 9200
    targetPort: 9200
    protocol: TCP
  selector:
    app: elasticsearch
