version: '3.4'

x-airflow-image: &airflow-image
  160358319781.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/reach:latest

x-env: &env
  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
  AWS_SESSION_TOKEN: "${AWS_SESSION_TOKEN}"

  SENTRY_DSN: "${SENTRY_DSN}"

services:
  scraper_nice:
    image: uk.ac.wellcome/reach/scraper:latest
    environment: *env
    entrypoint:
      - /opt/scraper/spider_task.py
      - "s3://datalabs-dev/split-scraper/results"
      - nice
